# 這個文件用來初始化 script 要使用的項目，設定值作用於 http

# set the lua files search paths.
lua_package_path "${prefix}script/?.ljbc;${prefix}script/?.lua;${prefix}script/resty/lib/?.lua;;";

# 設定 shared_dict
# lua_shared_dict  your_dict_name  10m;


init_by_lua_block {

}

init_worker_by_lua_block {

}
