local _M = {}
do
  _M.ERROR_CODE = {
    OK                    = 'OK',
    NOP                   = 'NOP',
    UNSUPPORTED           = 'UNSUPPORTED',
    NO_CONTENT            = 'NO_CONTENT',
    INVALID_OPERATION     = 'INVALID_OPERATION',

    UNKNOWN_FAILURE       = 'UNKNOWN_FAILURE',
    INVALID_ARGUMENT      = 'INVALID_ARGUMENT',
    PERMISSION_DENIED     = 'PERMISSION_DENIED',

    UPSTREAM_ERROR        = 'UPSTREAM_ERROR',

    INVALID_TOKEN         = 'INVALID_TOKEN',
    TOKEN_EXPIRED         = 'TOKEN_EXPIRED',

    MISSING_PRINCIPAL     = 'MISSING_PRINCIPAL',
    INVALID_PRINCIPAL     = 'INVALID_PRINCIPAL',
    INVALID_SIGNATURE     = 'INVALID_SIGNATURE',

    DUPLICATE_OPERATION   = 'DUPLICATE_OPERATION',
  }

end
return _M
